kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{oc_app_name}}
  namespace: {{oc_project}}
spec:
  replicas: 1
  selector:
    deploymentConfig: {{oc_app_name}}
    name: {{oc_app_name}}
  template:
    metadata:
      labels:
        deploymentConfig: {{oc_app_name}}
        name: {{oc_app_name}}
    spec:
      volumes:
        - name: nexus-pv
          emptyDir: {}
      containers:
        - name: {{oc_app_name}}
          image: >-
            image-registry.openshift-image-registry.svc:5000/{{oc_project}}/{{oc_app_name}}:latest
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nexus-pv
              mountPath: /tmp/local/config
