kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${oc_app_name}
  namespace: ${oc_project}
spec:
  host: >-
    $oc.app.name-apcdevpoc-project-dev.apps.apcdev.openshift.scalabs.cloud
  to:
    kind: Service
    name: ${oc_app_name}
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  wildcardPolicy: None
