kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{rootProject.name}}
  namespace: {{oc.project}}
spec:
  host: >-
    {{rootProject.name}}.apps.apcdev.openshift.scalabs.cloud
  to:
    kind: Service
    name: {{rootProject.name}}
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  wildcardPolicy: None