kind: Service
apiVersion: v1
metadata:
  name: rest-api-sample-develop
  namespace: apcdevpoc-project-dev
  labels:
    app: rest-api-sample-develop
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: ClientIP
  selector:
    deploymentConfig: rest-api-sample-develop
