kind: Service
apiVersion: v1
metadata:
  name: {{rootProject.name}}
  namespace: {{oc.project}}
  labels:
    app: {{rootProject.name}}
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: ClientIP
  selector:
    deploymentConfig: {{rootProject.name}}
